In [2]:
import numpy as np

# 1. Create an array of 10 fives
array1 = np.full(10, 5)
print("1.", array1)

# 2. Create an array of the integers from 10 to 50
array2 = np.arange(10, 51)
print("2.", array2)

# 3. Create an array of all the even integers from 10 to 50
array3 = np.arange(10, 51, 2)
print("3.", array3)

# 4. Create a 3x3 matrix with values ranging from 0 to 8
array4 = np.arange(9).reshape(3, 3)
print("4.", array4)

# 5. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
array5 = np.random.randn(25)
print("5.", array5)

# 6. Create a specific array
array6 = np.arange(0, 1.01, 0.01)
print("6.", array6)

# 7. Create an array of 20 linearly spaced points between 0 and 1
array7 = np.linspace(0, 1, 20)
print("7.", array7)

# 8. Generate the given matrix mat
mat = np.arange(1, 26).reshape(5, 5)
print("8.")
print(mat)

# Extracting specific portions using indexing and slicing
extract1 = mat[1:4, 1:5]
print("Extract 1:\n", extract1)

extract2 = mat[[1, 2, 3], [1]]
print("Extract 2:\n", extract2.reshape(-1, 1))

# Get the sum of all the values in mat
print("Sum of all values in mat:", np.sum(mat))

# Get the sum of all the rows and columns in mat
row_sums = np.sum(mat, axis=1)
print("Sum of rows in mat:", row_sums)

col_sums = np.sum(mat, axis=0)
print("Sum of columns in mat:", col_sums)


1. [5 5 5 5 5 5 5 5 5 5]
2. [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
3. [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
4. [[0 1 2]
 [3 4 5]
 [6 7 8]]
5. [ 0.64572938 -0.23265983 -0.00270732  1.10506907 -0.93430718  0.66756412
 -0.49039008 -0.16336412  1.19699582 -1.53459873  0.23820423  0.481367
 -1.38831159  1.53145826  0.23195172 -0.96940811  0.63348314 -0.02338996
 -0.61385886 -0.52398839  0.28218331 -0.21472443 -0.08857162  0.47295259
  1.04232936]
6. [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [7]:
array1 = np.full(10, 5)
print(array1)

[5 5 5 5 5 5 5 5 5 5]


In [8]:
l=[1,2,4,3,6,3,5,9]

In [13]:
ar=np.array(l)

In [11]:
type(ar)

numpy.ndarray

In [15]:
np.asarray(l)

array([1, 2, 4, 3, 6, 3, 5, 9])

In [14]:
ar

array([1, 2, 4, 3, 6, 3, 5, 9])

In [22]:
a=np.full(10,5)
print('2.',a)

2. [5 5 5 5 5 5 5 5 5 5]


In [26]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [27]:
np.matrix(l)

matrix([[1, 2, 4, 3, 6, 3, 5, 9]])

In [28]:
ar.ndim

1

In [30]:
ar.size

8

In [32]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [33]:
type(mat)

numpy.ndarray

In [2]:
import numpy as np
arr = np.random.randn(3,4)

In [4]:
type(arr)

numpy.ndarray

In [6]:
mat = np.arange(1, 26).reshape(5, 5)
print("8.")
print(mat)


8.
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [7]:
extract1 = mat[1:4, 1:5]

In [9]:
extract1

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])